#!/usr/bin/env node
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'fs'
import { join, resolve } from 'path'
import { fileURLToPath } from 'url'

const INFRA = fileURLToPath(new URL('.', import.meta.url))
const ROOT = resolve(INFRA, '..')
const APPS_DIR = join(ROOT, 'apps')
const WIDGETS_DIR = join(ROOT, 'widgets')

function readManifests(baseDir, filename) {
  if (!existsSync(baseDir)) return []
  return readdirSync(baseDir, { withFileTypes: true })
    .filter(e => e.isDirectory())
    .flatMap(dir => {
      const path = join(baseDir, dir.name, filename)
      if (!existsSync(path)) return []
      try {
        return [{ ...JSON.parse(readFileSync(path, 'utf8')), _dir: join(baseDir, dir.name) }]
      } catch {
        console.warn(`  Warning: failed to parse ${path}`)
        return []
      }
    })
}

// ── Nginx ──────────────────────────────────────────────────────────────────

function nginxLocation(path, upstream, { websocket = false, cors = false, maxBodySize = null } = {}) {
  const ws = websocket ? `
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";` : ''

  // CORS: handle OPTIONS preflight then add Allow-Origin to all proxied responses.
  const corsBlock = cors ? `
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Allow-Methods' 'GET, PUT, DELETE, HEAD, OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' '*' always;
            add_header 'Access-Control-Max-Age' '3000' always;
            add_header 'Content-Length' '0' always;
            return 204;
        }
        add_header 'Access-Control-Allow-Origin' '*' always;` : ''

  // maxBodySize: remove nginx body size limit and stream request body to upstream.
  // Set to "0" for unlimited (e.g. file upload endpoints).
  const sizeBlock = maxBodySize !== null ? `
        client_max_body_size ${maxBodySize};
        proxy_request_buffering off;` : ''

  // Use a variable so nginx resolves the upstream per-request (via Docker DNS)
  // rather than at startup — prevents boot failure when a service isn't up yet.
  return `
    location ${path} {${corsBlock}${sizeBlock}
        set $upstream ${upstream};
        proxy_pass http://$upstream;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;${ws}
    }`
}

function generateNginx(apps, widgets) {
  const routes = [...apps, ...widgets]
    .flatMap(m => m.nginx?.routes ?? [])
    .sort((a, b) => b.path.length - a.path.length) // longest path first for readability

  const blocks = routes.map(r => nginxLocation(r.path, r.upstream, r))

  return `# Redirect nucleus.home HTTP traffic to HTTPS (external access with TLS cert)
server {
    listen 80;
    server_name nucleus.home;
    return 301 https://nucleus.home$request_uri;
}

# Main server — HTTPS for nucleus.home, plain HTTP for localhost / IP access
server {
    listen 80 default_server;
    listen 443 ssl;
    server_name _;

    ssl_certificate /etc/ssl/certs/nucleus.crt;
    ssl_certificate_key /etc/ssl/private/nucleus.key;

    # Docker's internal DNS — lets nginx start even when optional services aren't up yet
    resolver 127.0.0.11 valid=10s ipv6=off;

    location /api/registry {
        proxy_pass http://registry:4000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
${blocks.join('\n')}

    location ~* ^(/watchlist)?/favicon\\.ico$ {
        root /usr/share/nginx/static;
        try_files /favicon.ico =404;
    }

    location / {
        proxy_pass http://hub:5174;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
    }
}
`
}

// ── Compose override ───────────────────────────────────────────────────────

// Apps with a top-level src/ are hub libraries (not standalone clients).
// Their src is mounted into the hub container so the @<id> vite alias resolves.
function findHubLibraries() {
  if (!existsSync(APPS_DIR)) return []
  return readdirSync(APPS_DIR, { withFileTypes: true })
    .filter(e => e.isDirectory() && existsSync(join(APPS_DIR, e.name, 'src')))
    .map(e => ({ id: e.name, rel: `../apps/${e.name}/src` }))
}

function generateOverride(apps, widgets, hubLibs) {
  const includes = [...apps, ...widgets]
    .filter(m => existsSync(join(m._dir, 'docker-compose.app.yml')))
    .map(m => {
      const rel = '../' + m._dir.slice(ROOT.length + 1).replace(/\\/g, '/')
      return `  - path: ${rel}/docker-compose.app.yml`
    })

  const hubVolumes = hubLibs.map(l => `      - ${l.rel}:/app/${l.id}:ro`)

  const parts = ['# GENERATED by infra/generate.js — do not edit manually']

  if (includes.length > 0) {
    parts.push(`include:\n${includes.join('\n')}`)
  }

  if (hubVolumes.length > 0) {
    parts.push(`services:\n  hub:\n    volumes:\n${hubVolumes.join('\n')}`)
  }

  return parts.join('\n\n') + '\n'
}

// ── Main ───────────────────────────────────────────────────────────────────

const apps = readManifests(APPS_DIR, 'nucleus.app.json')
const widgets = readManifests(WIDGETS_DIR, 'nucleus.widget.json')
const hubLibs = findHubLibraries()

console.log(`Apps:    ${apps.length ? apps.map(a => a.id).join(', ') : 'none'}`)
console.log(`Widgets: ${widgets.length ? widgets.map(w => w.id).join(', ') : 'none'}`)
console.log(`Hub libs: ${hubLibs.length ? hubLibs.map(l => l.id).join(', ') : 'none'}`)

writeFileSync(join(INFRA, 'nginx', 'nginx.conf'), generateNginx(apps, widgets))
console.log('→ nginx/nginx.conf')

writeFileSync(join(INFRA, 'docker-compose.override.yml'), generateOverride(apps, widgets, hubLibs))
console.log('→ docker-compose.override.yml')
