#!/usr/bin/env node
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'fs'
import { join, resolve } from 'path'
import { fileURLToPath } from 'url'

const INFRA = fileURLToPath(new URL('.', import.meta.url))
const ROOT = resolve(INFRA, '..')
const APPS_DIR = join(ROOT, 'apps')
const WIDGETS_DIR = join(ROOT, 'widgets')

function readManifests(baseDir, filename) {
  if (!existsSync(baseDir)) return []
  return readdirSync(baseDir, { withFileTypes: true })
    .filter(e => e.isDirectory())
    .flatMap(dir => {
      const path = join(baseDir, dir.name, filename)
      if (!existsSync(path)) return []
      try {
        return [{ ...JSON.parse(readFileSync(path, 'utf8')), _dir: join(baseDir, dir.name) }]
      } catch {
        console.warn(`  Warning: failed to parse ${path}`)
        return []
      }
    })
}

// ── Nginx ──────────────────────────────────────────────────────────────────

function nginxLocation(path, upstream, websocket = false) {
  const ws = websocket ? `
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";` : ''
  // Use a variable so nginx resolves the upstream per-request (via Docker DNS)
  // rather than at startup — prevents boot failure when a service isn't up yet.
  return `
    location ${path} {
        set $upstream ${upstream};
        proxy_pass http://$upstream;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;${ws}
    }`
}

function generateNginx(apps, widgets) {
  const routes = [...apps, ...widgets]
    .flatMap(m => m.nginx?.routes ?? [])
    .sort((a, b) => b.path.length - a.path.length) // longest path first for readability

  const blocks = routes.map(r => nginxLocation(r.path, r.upstream, r.websocket))

  return `server {
    listen 80 default_server;
    server_name nucleus.home;

    # Docker's internal DNS — lets nginx start even when optional services aren't up yet
    resolver 127.0.0.11 valid=10s ipv6=off;

    location /api/registry {
        proxy_pass http://registry:4000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
${blocks.join('\n')}

    location ~* ^(/watchlist)?/favicon\\.ico$ {
        root /usr/share/nginx/static;
        try_files /favicon.ico =404;
    }

    location / {
        proxy_pass http://hub:5174;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
    }
}
`
}

// ── Compose override ───────────────────────────────────────────────────────

function generateOverride(apps, widgets) {
  const includes = [...apps, ...widgets]
    .filter(m => existsSync(join(m._dir, 'docker-compose.app.yml')))
    .map(m => {
      // Paths relative to infra/ (where docker-compose.yml lives)
      const rel = '../' + m._dir.slice(ROOT.length + 1).replace(/\\/g, '/')
      return `  - path: ${rel}/docker-compose.app.yml`
    })

  if (includes.length === 0) return '# No app/widget compose files discovered\n'

  return `# GENERATED by infra/generate.js — do not edit manually
include:
${includes.join('\n')}
`
}

// ── Main ───────────────────────────────────────────────────────────────────

const apps = readManifests(APPS_DIR, 'nucleus.app.json')
const widgets = readManifests(WIDGETS_DIR, 'nucleus.widget.json')

console.log(`Apps:    ${apps.length ? apps.map(a => a.id).join(', ') : 'none'}`)
console.log(`Widgets: ${widgets.length ? widgets.map(w => w.id).join(', ') : 'none'}`)

writeFileSync(join(INFRA, 'nginx', 'nginx.conf'), generateNginx(apps, widgets))
console.log('→ nginx/nginx.conf')

writeFileSync(join(INFRA, 'docker-compose.override.yml'), generateOverride(apps, widgets))
console.log('→ docker-compose.override.yml')
